# Generated by Django 5.1.6 on 2025-02-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_id', models.IntegerField(db_comment='类型外键引用')),
                ('used_n', models.IntegerField(db_comment='被使用次数')),
            ],
            options={
                'db_table': 'data_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataTemplateCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'data_template_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataTemplateDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_template_id', models.IntegerField(db_comment='模�\x9d�外键')),
                ('item_name', models.CharField(max_length=255)),
                ('item_name_code', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=255)),
                ('category_name_code', models.CharField(max_length=255)),
                ('type_name', models.CharField(max_length=255)),
                ('type_name_code', models.CharField(max_length=255)),
                ('order_index', models.IntegerField()),
            ],
            options={
                'db_table': 'data_template_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataTemplateTags',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'data_template_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataTemplateTagsRelative',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('template_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
            ],
            options={
                'db_table': 'data_template_tags_relative',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_code', models.CharField(db_comment='�\x8d�\x9d�编�\x8f�', max_length=255)),
                ('word_name', models.CharField(db_comment='�\xad文�\x90\x8d称', max_length=255)),
                ('word_eng', models.CharField(blank=True, db_comment='英文�\x90\x8d称', max_length=255, null=True)),
                ('word_short', models.CharField(blank=True, db_comment='英文缩写', max_length=255, null=True)),
                ('word_class', models.CharField(db_comment='�\x8d�\x9d�类型', max_length=255)),
                ('word_apply', models.CharField(db_comment='�\x8d�\x9d�应用', max_length=255)),
                ('word_belong', models.CharField(blank=True, db_comment='从属别�\x90\x8d', max_length=255, null=True)),
            ],
            options={
                'db_table': 'dictionary',
                'managed': False,
            },
        ),
    ]
