# Generated by Django 5.1.6 on 2025-02-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSheet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sheet_code', models.CharField(db_comment='�\x8f机生�\x90', max_length=255)),
                ('sheet_name', models.CharField(max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'analysis_sheet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisSheetDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('case_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('item_value', models.CharField(max_length=255)),
                ('item_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'analysis_sheet_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=255)),
                ('extract_cases', models.CharField(max_length=255)),
                ('since_start', models.DateField()),
                ('since_end', models.DateField()),
                ('data_template_id', models.IntegerField()),
                ('constraint', models.CharField(blank=True, db_comment='约�\x9d��\x9d�件', max_length=255, null=True)),
                ('load_times', models.DateTimeField(blank=True, db_comment='数�\x8d��\xa0载次数', null=True)),
                ('last_load_date', models.DateTimeField(blank=True, db_comment='最�\x90��\xa0载时间', null=True)),
            ],
            options={
                'db_table': 'analysis_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('analysis_sheet_id', models.IntegerField(db_comment='数�\x8d��\x90')),
                ('selected_cases', models.CharField(max_length=255)),
                ('selected_attrs', models.CharField(max_length=255)),
                ('mapping', models.CharField(db_comment='数�\x8d��\xa0射，�\xad�JSON', max_length=255)),
                ('axis', models.CharField(db_comment='�\x9d\x90�\xa0�轴，�\xad�JSON', max_length=255)),
                ('options', models.CharField(db_comment='常规�\x8d置，�\xad�JSON', max_length=255)),
            ],
            options={
                'db_table': 'charts',
                'managed': False,
            },
        ),
    ]
