# Generated by Django 5.1.6 on 2025-02-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('arcive_id', models.CharField(max_length=255)),
                ('archive_name', models.CharField(db_comment='专病档案�\x90\x8d称', max_length=255)),
                ('description', models.TextField(blank=True, db_comment='专病档案说明', null=True)),
            ],
            options={
                'db_table': 'archive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchiveCaseRelative',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('archive_id', models.CharField(max_length=255)),
                ('case_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'archive_case_relative',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('case_id', models.CharField(db_comment='病历外键引用', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_code', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('category_code', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('type_code', models.CharField(max_length=255)),
                ('value', models.CharField(db_comment='值', max_length=255)),
            ],
            options={
                'db_table': 'base_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=255)),
                ('identity_id', models.CharField(max_length=255)),
                ('inhospital_id', models.CharField(blank=True, db_comment='�\x8f院�\x8f�', max_length=255, null=True)),
            ],
            options={
                'db_table': 'cases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_code', models.CharField(max_length=255)),
                ('case_id', models.CharField(db_comment='病历�\x8f�外键', max_length=255)),
            ],
            options={
                'db_table': 'clinical_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identity_id', models.CharField(db_comment='身份�\x81�\x8f�', max_length=255, unique=True)),
                ('true_name', models.CharField(db_comment='真实姓�\x90\x8d', max_length=255)),
                ('gender', models.IntegerField(db_comment='性别')),
                ('birth_date', models.DateTimeField(db_comment='出生年月日')),
            ],
            options={
                'db_table': 'identity',
                'managed': False,
            },
        ),
    ]
